"""Canva handoff helpers for generated label data."""

import json
from typing import List, Optional

from .schema import GHS_PICTOGRAM_OPTIONS, normalize_ghs_pictogram

CANVA_TEMPLATE_NAME = "ClearEdge Product Label Template"


CANVA_TEMPLATE_FIELDS = {
    "label_id": "Stable generated label ID.",
    "product_name": "ClearEdge product name printed as the main label title.",
    "product_name_display": "Alias for the Canva product title placeholder.",
    "label_mode": "shipped_dot or workplace.",
    "label_size": "pail, drum, or tote selection retained for source data.",
    "label_orientation": "vertical or horizontal print orientation.",
    "container_type": "Container inferred from weight: pail, drum, or tote.",
    "lot_number": "Shipment lot or batch number.",
    "lot_number_display": "Lot number formatted for large visual label text.",
    "expiration_date": "Expiration date for the shipment.",
    "expiration_date_display": "Expiration date formatted for large visual label text.",
    "fill_amount": "Net contents, including units such as lb or kg.",
    "fill_amount_display": "Fill amount formatted for large visual label text.",
    "manufacture_date": "Manufacture date, when supplied.",
    "supplier_name": "Supplier or manufacturer name.",
    "supplier_address": "Supplier or manufacturer address.",
    "supplier_phone": "Supplier phone.",
    "emergency_phone": "Emergency phone from SDS, when available.",
    "sds_revision_date": "SDS revision date, when available.",
    "signal_word": "Exact GHS signal word.",
    "signal_word_display": "Signal word formatted for the label.",
    "ghs_pictograms": "Comma-separated GHS pictogram codes.",
    "ghs_pictogram_names": "Comma-separated GHS pictogram names.",
    "ghs_pictogram_1_code": "First GHS pictogram code.",
    "ghs_pictogram_1_name": "First GHS pictogram name.",
    "ghs_pictogram_2_code": "Second GHS pictogram code.",
    "ghs_pictogram_2_name": "Second GHS pictogram name.",
    "ghs_pictogram_3_code": "Third GHS pictogram code.",
    "ghs_pictogram_3_name": "Third GHS pictogram name.",
    "ghs_pictogram_4_code": "Fourth GHS pictogram code.",
    "ghs_pictogram_4_name": "Fourth GHS pictogram name.",
    "hazard_statements": "Pipe-separated H-code statements.",
    "precautionary_statements": "Pipe-separated P-code statements.",
    "supplemental_statements": "Pipe-separated supplemental hazard statements.",
    "un_number": "UN/NA number.",
    "un_number_display": "UN/NA number formatted for the DOT block.",
    "transport_not_regulated": "True when SDS says the product is not regulated for transport.",
    "proper_shipping_name": "DOT proper shipping name.",
    "proper_shipping_name_display": "DOT proper shipping name formatted for the label.",
    "hazard_class": "DOT hazard class.",
    "hazard_class_display": "DOT hazard class formatted for the label.",
    "dot_hazard_label": "Supported DOT label wording.",
    "packing_group": "DOT packing group.",
    "packing_group_display": "DOT packing group formatted for the label.",
    "marine_pollutant": "Marine pollutant value.",
    "limited_quantity": "Limited quantity value.",
    "transport_summary": "Concise transport summary for a Canva text block.",
    "special_provisions": "DOT special provisions.",
    "erg_guide_number": "ERG guide number.",
    "nfpa_health": "NFPA health number.",
    "nfpa_flammability": "NFPA flammability number.",
    "nfpa_instability": "NFPA instability/reactivity number.",
    "nfpa_special": "NFPA special code.",
    "nfpa_704_summary": "NFPA values in one compact string.",
    "validation_status": "ready, blocked, needs_review, or override_approved.",
    "override_approved": "True when an operator override enabled the label.",
    "override_approver": "Override approver text.",
    "override_reason": "Override reason text.",
}


def canva_template_manifest() -> dict:
    """Return the field manifest operators should map in Canva Bulk Create."""
    return {
        "template_name": CANVA_TEMPLATE_NAME,
        "bulk_create_source": "CSV or JSON generated by ClearEdge Label Creator",
        "required_fields": [
            "product_name",
            "lot_number_display",
            "expiration_date_display",
            "fill_amount_display",
            "signal_word_display",
            "ghs_pictogram_1_code",
            "nfpa_health",
            "nfpa_flammability",
            "nfpa_instability",
        ],
        "fields": [
            {"name": name, "description": description}
            for name, description in CANVA_TEMPLATE_FIELDS.items()
        ],
    }


def canva_urls(label_id: str, available: bool) -> dict:
    """Return Canva handoff URLs only when export is allowed."""
    if not available:
        return {"canva_csv_url": None, "canva_json_url": None}
    return {
        "canva_csv_url": f"/api/v1/labels/{label_id}/canva-export.csv",
        "canva_json_url": f"/api/v1/labels/{label_id}/canva-export.json",
    }


def clean_operator_field(value: Optional[str]) -> Optional[str]:
    """Normalize optional operator-entered shipment fields."""
    if value is None:
        return None
    cleaned = " ".join(value.split())
    return cleaned or None


def parse_ghs_pictogram_selection(value: Optional[str]) -> List[str]:
    """Parse optional operator-selected GHS pictogram dropdown values."""
    cleaned = clean_operator_field(value)
    if not cleaned:
        return []

    try:
        parsed = json.loads(cleaned)
    except json.JSONDecodeError:
        parsed = cleaned

    if isinstance(parsed, str):
        raw_values = [
            item.strip()
            for item in parsed.replace("|", ",").replace(";", ",").split(",")
            if item.strip()
        ]
    elif isinstance(parsed, list):
        raw_values = parsed
    else:
        raise ValueError("GHS pictograms must be a list or comma-separated string")

    deduped = []
    seen = set()
    for raw_value in raw_values:
        code = normalize_ghs_pictogram(str(raw_value))
        if code not in seen:
            deduped.append(code)
            seen.add(code)
    return deduped


def build_canva_export(extracted: dict, metadata: dict) -> dict:
    """Create a flat, Canva Bulk Create-friendly label data record."""
    product = extracted.get("product") or {}
    ghs = extracted.get("ghs") or {}
    transport = extracted.get("transport") or {}
    nfpa = extracted.get("nfpa") or {}
    shipment = extracted.get("shipment") or {}
    pictograms = ghs.get("pictograms") or []
    nfpa_health = str(nfpa.get("health", 0))
    nfpa_flammability = str(nfpa.get("flammability", 0))
    nfpa_instability = str(nfpa.get("instability", 0))
    nfpa_special = nfpa.get("special") or ""
    un_number = transport.get("un_number") or ""
    proper_shipping_name = transport.get("proper_shipping_name") or ""
    hazard_class = transport.get("hazard_class") or ""
    packing_group = transport.get("packing_group") or ""
    return {
        "label_id": metadata.get("label_id") or "",
        "product_name": metadata.get("product_name") or product.get("name") or "",
        "product_name_display": metadata.get("product_name") or product.get("name") or "",
        "label_mode": metadata.get("mode") or "",
        "label_size": metadata.get("size") or "",
        "label_orientation": metadata.get("orientation") or "vertical",
        "container_type": metadata.get("container_type") or shipment.get("container_type") or "",
        "lot_number": shipment.get("lot_number") or "",
        "lot_number_display": shipment.get("lot_number") or "",
        "expiration_date": shipment.get("expiration_date") or "",
        "expiration_date_display": shipment.get("expiration_date") or "",
        "fill_amount": shipment.get("fill_amount") or "",
        "fill_amount_display": shipment.get("fill_amount") or "",
        "manufacture_date": shipment.get("manufacture_date") or "",
        "supplier_name": product.get("supplier_name") or "",
        "supplier_address": product.get("supplier_address") or "",
        "supplier_phone": product.get("supplier_phone") or "",
        "emergency_phone": product.get("emergency_phone") or "",
        "sds_revision_date": product.get("revision_date") or "",
        "signal_word": ghs.get("signal_word") or "",
        "signal_word_display": (ghs.get("signal_word") or "").upper(),
        "ghs_pictograms": ", ".join(pictograms),
        "ghs_pictogram_names": _ghs_pictogram_names(pictograms),
        **_pictogram_columns(pictograms),
        "hazard_statements": _format_statement_list(ghs.get("hazard_statements") or []),
        "precautionary_statements": _format_statement_list(ghs.get("precautionary_statements") or []),
        "supplemental_statements": " | ".join(ghs.get("supplemental_statements") or []),
        "un_number": un_number,
        "un_number_display": un_number,
        "transport_not_regulated": str(bool(transport.get("not_regulated"))),
        "proper_shipping_name": proper_shipping_name,
        "proper_shipping_name_display": proper_shipping_name,
        "hazard_class": hazard_class,
        "hazard_class_display": hazard_class,
        "dot_hazard_label": dot_hazard_label_name(hazard_class),
        "packing_group": packing_group,
        "packing_group_display": packing_group,
        "marine_pollutant": _optional_value(transport.get("marine_pollutant")),
        "limited_quantity": _optional_value(transport.get("limited_quantity")),
        "transport_summary": _transport_summary(transport),
        "special_provisions": _join_optional_values(transport.get("special_provisions")),
        "erg_guide_number": transport.get("erg_guide_number") or "",
        "nfpa_health": nfpa_health,
        "nfpa_flammability": nfpa_flammability,
        "nfpa_instability": nfpa_instability,
        "nfpa_special": nfpa_special,
        "nfpa_704_summary": (
            f"Health {nfpa_health} | Flammability {nfpa_flammability} | "
            f"Instability {nfpa_instability}"
            + (f" | Special {nfpa_special}" if nfpa_special else "")
        ),
        "validation_status": metadata.get("status") or "",
        "override_approved": str(bool(metadata.get("override_approved"))),
        "override_approver": metadata.get("override_approver") or "",
        "override_reason": metadata.get("override_reason") or "",
    }


def dot_hazard_label_name(hazard_class: Optional[str]) -> str:
    """Return supported DOT hazard label name for Canva handoff."""
    if not hazard_class:
        return ""
    clean = str(hazard_class).strip().lower()
    if "not regulated" in clean or "not applicable" in clean:
        return ""
    if clean.startswith("class "):
        clean = clean[6:]
    if "3" in clean:
        return "FLAMMABLE LIQUID"
    if "8" in clean:
        return "CORROSIVE"
    if "9" in clean:
        return "CLASS 9"
    return "Review required"


def _optional_value(value) -> str:
    """Return a CSV-safe blank for missing optional values."""
    return "" if value is None else str(value)


def _join_optional_values(value) -> str:
    """Flatten optional scalar/list values into a single Canva cell."""
    if value is None:
        return ""
    if isinstance(value, list):
        return " | ".join(str(item).strip() for item in value if str(item).strip())
    return str(value)


def _format_statement_list(items: list) -> str:
    """Flatten GHS statement objects for Canva Bulk Create cells."""
    formatted = []
    for item in items or []:
        code = (item.get("code") or "").strip()
        text = (item.get("text") or "").strip()
        if code and text:
            formatted.append(f"{code}: {text}")
        elif text:
            formatted.append(text)
        elif code:
            formatted.append(code)
    return " | ".join(formatted)


def _ghs_pictogram_names(codes: list) -> str:
    """Return display names for GHS pictogram codes."""
    return ", ".join(GHS_PICTOGRAM_OPTIONS.get(code, code) for code in codes or [])


def _pictogram_columns(codes: list) -> dict:
    """Expose fixed Canva columns for up to four GHS pictograms."""
    columns = {}
    for index in range(1, 5):
        code = codes[index - 1] if len(codes) >= index else ""
        columns[f"ghs_pictogram_{index}_code"] = code
        columns[f"ghs_pictogram_{index}_name"] = GHS_PICTOGRAM_OPTIONS.get(code, code) if code else ""
    return columns


def _transport_summary(transport: dict) -> str:
    """Create a compact transport text block for Canva templates."""
    if transport.get("not_regulated"):
        return "Not regulated for transport"

    parts = []
    un_number = transport.get("un_number")
    proper_shipping_name = transport.get("proper_shipping_name")
    hazard_class = transport.get("hazard_class")
    packing_group = transport.get("packing_group")

    if un_number:
        parts.append(str(un_number))
    if proper_shipping_name:
        parts.append(str(proper_shipping_name))
    if hazard_class:
        parts.append(f"Class {hazard_class}")
    if packing_group:
        parts.append(f"PG {packing_group}")
    return " | ".join(parts)
